name: Run code validation checks
on:
  - push
  - pull_request

jobs:
  coding-standard-validation:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        php-version:
          - "8.1"
        dependencies:
          - "highest"
        composer-options:
          - "--no-plugins"
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/checkout@v2

      - name: Setup Php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-file: development
        env:
          COMPOSER_AUTH_JSON: |
            {
              "http-basic": {
                "repo.magento.com": {
                  "username": "${{ secrets.REPO_MAGENTO_USER }}",
                  "password": "${{ secrets.REPO_MAGENTO_PASSWORD }}"
                }
              }
            }

      - name: Validate Composer Files
        run: composer validate

      - name: Run Composer install
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "${{ matrix.composer-options }}"

      - name: Configure coding standard
        run: vendor/bin/phpcs --config-set installed_paths ../../magento/magento-coding-standard/

      - name: Run code style suite
        run: vendor/bin/phpcs -q --report=checkstyle # TODO add cs2pr